objects/Contact/fields/Darce__c.field-meta.xml
<CustomField>
    <fullName>Darce__c</fullName>
    <description>Je dárce nebo na něm pracujeme</description>
    <inlineHelpText>Je dárce nebo na něm pracujeme</inlineHelpText>
    <label>Stav dárce</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dárce</fullName>
            </value>
            <value>
                <fullName>Potenciální dárce</fullName>
            </value>
            <value>
                <fullName>Nechce darovat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Dar__c/Dar__c.object-meta.xml
<CustomObject>
    <description>Jednotlivý příspěvek od dárce.</description>
    <label>Dar</label>
    <nameField>
        <label>Dar</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dary</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Dar__c/fields/darce__c.field-meta.xml
<CustomField>
    <fullName>darce__c</fullName>
    <label>Dárce</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dary</relationshipLabel>
    <relationshipName>Dary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Dar__c/fields/Darovana_castka__c.field-meta.xml
<CustomField>
    <fullName>Darovana_castka__c</fullName>
    <label>Darovaná částka</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

objects/Kampan__c/Kampan__c.object-meta.xml
<CustomObject>
    <label>Kampaň</label>
    <nameField>
        <label>Název kampaně</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kampaně</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/trigger-handlers/DarTriggerHandler.cls
public class DarTriggerHandler {
    
    /**
     * Adds contact to campaign to which the new donation was donated
     */
    public static void addDonorsToCampaigns(List<Dar__c> dary) {
        Set<CampaignMember> membersToAdd = new Set<CampaignMember>();

        Map<Id, List<Id>> contactToCampaigns = CampaignMemberHandler.getContactsCampaignsMap(Utils.mapToId(dary, Dar__c.Darce__c));

        for (Dar__c dar: dary) {
            if (!contactToCampaigns.containsKey(dar.Darce__c) || !contactToCampaigns.get(dar.Darce__c).contains(dar.Kampan__c)) {
                membersToAdd.add(new CampaignMemberHandler()
                    .setCampaignId(dar.Kampan__c)
                    .setContactId(dar.Darce__c)
                    .build()
                );
            }
        }

        DatabaseManager.insertListPartialEnabled(new List<CampaignMember>(membersToAdd));
    }


    /**
    * Marks contact as recurrent donor if the transactions was part of recurrent pledge
    */
    public static void markRecurrentDonors(List<Dar__c> dary) {
        Map<Id, Contact> contactsToUpdate = new Map<Id, Contact>();

        for (Dar__c dar: dary) {
            if (dar.Pravidelny_dar__c && !contactsToUpdate.containsKey(dar.darce__c)) {
                contactsToUpdate.put(dar.darce__c, new Contact(
                    Id = dar.darce__c,
                    Pravidelny_darce__c = true,
                    Prislibena_castka__c = dar.Darovana_castka__c
                ));
            }
        }

        DatabaseManager.updateListPartialEnabled(contactsToUpdate.values());
    }
}